from .orderline_pattern.orderline_pattern import orderline_pattern_page
from .abc_classification.abc_classification import abc_classification_page
from .general_profile.general_profile import general_outbound_page