from copy import deepcopy

import streamlit as st
import pandas as pd

# Main app imports
from . import are_there_dataframes, no_dataframe_yet
# Local folder imports
from . import utils as ut
from .report_generator import dataset_report
from .report_dashboard import general_outbound_dashboard
from .export_data import export_data_page
from apps.widgets import dtframe
# Constants
from .settings import *

def initialize_data():
    # All data generated by this app will be store here
    if GENERAL_PROFILE not in st.session_state:
        st.session_state[GENERAL_PROFILE] = dict()

def select_outbound_dataframe():
    global file_name, df
    file_name, df = dtframe.select_dataframe('Outbound Dataframe')
    dtframe.display_dataframe(df, file_name)
    st.markdown('---')

def select_orderline_relevant_columns():
    st.markdown('### Select Relevant Columns')
    options = list(df.columns)
    qty_col = st.selectbox('Select Quantity Column:', options)
    options = deepcopy(options)
    options.remove(qty_col)
    sku_col = st.selectbox('Select SKU Column:', options)
    options = deepcopy(options)
    options.remove(sku_col)
    order_col = st.selectbox('Select Order Reference Column:', options)
    # Pack selection
    selected_cols = {
        QTY:qty_col,
        N_OLS: sku_col,
        N_ORDERS: order_col,
    }
    st.markdown('---')
    return selected_cols

def main_section(selected_cols: dict):
    tab1, tab2, tab3 = st.tabs(['Generate Report(s)', 'Dashboard', 'Export Data'])

    with tab1:
        dataset_report(df, selected_cols)

    with tab2:
        general_outbound_dashboard()

    with tab3:
        export_data_page()

def page_intro():
    st.markdown('## General Outbound Overview')
    with st.expander('More Info'):
        text = """
        
        Outbound overview is designed to help logistics engineers visualize and analyze outbound data. 
        It provides a user-friendly interface to generate detailed reports, create interactive dashboards, and export processed data. 

        **Key Features**:
        1. **Orderline Analysis**: Visualize daily orderlines and analyze their distribution using percentiles.
        2. **Outbound Statistics**: Display key metrics such as total orders, orderlines, and SKUs.
        3. **Interactive Dashboards**: Create interactive charts and heatmaps to explore data trends.
        4. **Percentile Removal**: Analyze the impact of removing orderlines below a certain percentile.
        5. **Export Data**: Export the processed data for further analysis or sharing.
        
        By using this tool, you can ensure that your outbound data is well-structured and ready for analysis, helping you make informed decisions and optimize your logistics operations.
        """
        st. markdown(text)

def general_outbound_page():
    initialize_data()
    page_intro()
    if are_there_dataframes():
        select_outbound_dataframe()
        selected_cols = select_orderline_relevant_columns()
        main_section(selected_cols)
    else:
        no_dataframe_yet()